"""
Prompt templates for Gemini quiz generation.
"""


def build_quiz_prompt(transcript: str) -> str:
    """
    Build the prompt for Gemini.

    Args:
        transcript: Transcript generated by Whisper.

    Returns:
        Formatted prompt string.
    """
    return f"""
You are an expert educational quiz generator.

Your task is to create a quiz ONLY from the transcript below.

IMPORTANT RULES:

- Respond ONLY with valid JSON.
- Do NOT use markdown.
- Do NOT wrap the JSON in ``` blocks.
- Do NOT explain anything.
- Do NOT add any extra text.
- The JSON must be valid.
- Generate EXACTLY 10 questions.
- Each question MUST contain EXACTLY 4 answer options.
- ONLY ONE answer is correct.
- The correct answer MUST exactly match one option.
- Create a short descriptive title.
- Create a short description.
- Questions should test understanding of the transcript.
- Questions should not be duplicated.
- Answer options should be realistic.
- Use the same language as the transcript.

Return ONLY this JSON format:

{{
    "title": "Quiz Title",
    "description": "Short quiz description",
    "questions": [
        {{
            "question_title": "Question text",
            "question_options": [
                "Option A",
                "Option B",
                "Option C",
                "Option D"
            ],
            "answer": "Option A"
        }}
    ]
}}

Transcript:

{transcript}
"""