"""
Service for generating quizzes with Gemini AI.
"""

import json

from django.conf import settings
from google import genai

from quizzes.utils.exceptions import (
    GeminiGenerationError,
    InvalidQuizJsonError,
)
from quizzes.utils.prompts import build_quiz_prompt


MODEL_NAME = "gemini-flash-latest"


def generate_quiz(transcript: str) -> dict:
    """
    Generate quiz data from transcript using Gemini.

    Args:
        transcript: Text generated by Whisper.

    Returns:
        Quiz data as dictionary.

    Raises:
        GeminiGenerationError: If Gemini request fails.
        InvalidQuizJsonError: If response JSON is invalid.
    """
    client = genai.Client(
        api_key=settings.GEMINI_API_KEY
    )

    prompt = build_quiz_prompt(transcript)

    try:
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt,
            config={
                "response_mime_type": "application/json",
            },
        )
    except Exception as error:
        raise GeminiGenerationError(
            "Gemini request failed."
        ) from error

    try:
        quiz_data = json.loads(response.text)
    except json.JSONDecodeError as error:
        raise InvalidQuizJsonError(
            "Gemini returned invalid JSON."
        ) from error

    validate_quiz_structure(quiz_data)

    return quiz_data


def validate_quiz_structure(quiz_data: dict) -> None:
    """
    Validate generated quiz JSON structure.

    Args:
        quiz_data: Generated quiz dictionary.

    Raises:
        InvalidQuizJsonError: If structure is invalid.
    """
    questions = quiz_data.get("questions")

    if not questions or len(questions) != 10:
        raise InvalidQuizJsonError(
            "Quiz must contain exactly 10 questions."
        )

    for question in questions:
        validate_question(question)


def validate_question(question: dict) -> None:
    """
    Validate single quiz question.

    Args:
        question: Question dictionary.

    Raises:
        InvalidQuizJsonError: If question is invalid.
    """
    options = question.get("question_options")
    answer = question.get("answer")

    if not options or len(options) != 4:
        raise InvalidQuizJsonError(
            "Each question needs exactly 4 options."
        )

    if answer not in options:
        raise InvalidQuizJsonError(
            "Answer must match one option."
        )